name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'
      - name: Build and test
        run: |
          export SHELL=/bin/bash
          chmod 777 ./gradlew
          ./gradlew build
          docker build -t carsjava
          docker run -p 5000:8080 carsjava
          curl --header "Content-Type: application/json" --request GET http://localhost:5000/cars